# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-28T13:08:34+00:00

from __future__ import annotations

from datetime import datetime
from enum import Enum
from typing import Any, List, Optional

from pydantic import BaseModel, Field, RootModel, conint, constr


class Boolean(RootModel[bool]):
    root: bool


class DateTime(RootModel[datetime]):
    root: datetime


class DeletePermissionRequest(BaseModel):
    pass


class DeletePermissionVersionRequest(BaseModel):
    pass


class DeleteResourceShareRequest(BaseModel):
    pass


class EnableSharingWithAwsOrganizationRequest(BaseModel):
    pass


class EnableSharingWithAwsOrganizationResponse(BaseModel):
    returnValue: Optional[Boolean] = None


class IdempotentParameterMismatchException(RootModel[Any]):
    root: Any


class Integer(RootModel[int]):
    root: int


class InvalidClientTokenException(RootModel[Any]):
    root: Any


class InvalidMaxResultsException(RootModel[Any]):
    root: Any


class InvalidNextTokenException(RootModel[Any]):
    root: Any


class InvalidParameterException(RootModel[Any]):
    root: Any


class InvalidPolicyException(RootModel[Any]):
    root: Any


class InvalidResourceTypeException(RootModel[Any]):
    root: Any


class InvalidStateTransitionException(RootModel[Any]):
    root: Any


class MalformedArnException(RootModel[Any]):
    root: Any


class MalformedPolicyTemplateException(RootModel[Any]):
    root: Any


class MaxResults(RootModel[conint(ge=1, le=500)]):
    root: conint(ge=1, le=500)


class MissingRequiredParameterException(RootModel[Any]):
    root: Any


class OperationNotPermittedException(RootModel[Any]):
    root: Any


class PermissionAlreadyExistsException(RootModel[Any]):
    root: Any


class PermissionFeatureSet(Enum):
    CREATED_FROM_POLICY = 'CREATED_FROM_POLICY'
    PROMOTING_TO_STANDARD = 'PROMOTING_TO_STANDARD'
    STANDARD = 'STANDARD'


class PermissionLimitExceededException(RootModel[Any]):
    root: Any


class PermissionName(
    RootModel[constr(pattern=r'[\w.-]*', min_length=1, max_length=36)]
):
    root: constr(pattern=r'[\w.-]*', min_length=1, max_length=36)


class PermissionStatus(Enum):
    ATTACHABLE = 'ATTACHABLE'
    UNATTACHABLE = 'UNATTACHABLE'
    DELETING = 'DELETING'
    DELETED = 'DELETED'


class PermissionType(Enum):
    CUSTOMER_MANAGED = 'CUSTOMER_MANAGED'
    AWS_MANAGED = 'AWS_MANAGED'


class PermissionTypeFilter(Enum):
    ALL = 'ALL'
    AWS_MANAGED = 'AWS_MANAGED'
    CUSTOMER_MANAGED = 'CUSTOMER_MANAGED'


class PermissionVersionsLimitExceededException(RootModel[Any]):
    root: Any


class Policy(RootModel[str]):
    root: str


class PolicyList(RootModel[List[Policy]]):
    root: List[Policy]


class PromoteResourceShareCreatedFromPolicyRequest(BaseModel):
    pass


class PromoteResourceShareCreatedFromPolicyResponse(BaseModel):
    returnValue: Optional[Boolean] = None


class ReplacePermissionAssociationsWorkStatus(Enum):
    IN_PROGRESS = 'IN_PROGRESS'
    COMPLETED = 'COMPLETED'
    FAILED = 'FAILED'


class ResourceArnNotFoundException(RootModel[Any]):
    root: Any


class ResourceOwner(Enum):
    SELF = 'SELF'
    OTHER_ACCOUNTS = 'OTHER-ACCOUNTS'


class ResourceRegionScope(Enum):
    REGIONAL = 'REGIONAL'
    GLOBAL = 'GLOBAL'


class ResourceRegionScopeFilter(Enum):
    ALL = 'ALL'
    REGIONAL = 'REGIONAL'
    GLOBAL = 'GLOBAL'


class ResourceShareAssociationStatus(Enum):
    ASSOCIATING = 'ASSOCIATING'
    ASSOCIATED = 'ASSOCIATED'
    FAILED = 'FAILED'
    DISASSOCIATING = 'DISASSOCIATING'
    DISASSOCIATED = 'DISASSOCIATED'


class ResourceShareAssociationType(Enum):
    PRINCIPAL = 'PRINCIPAL'
    RESOURCE = 'RESOURCE'


class ResourceShareFeatureSet(Enum):
    CREATED_FROM_POLICY = 'CREATED_FROM_POLICY'
    PROMOTING_TO_STANDARD = 'PROMOTING_TO_STANDARD'
    STANDARD = 'STANDARD'


class ResourceShareInvitationAlreadyAcceptedException(RootModel[Any]):
    root: Any


class ResourceShareInvitationAlreadyRejectedException(RootModel[Any]):
    root: Any


class ResourceShareInvitationArnNotFoundException(RootModel[Any]):
    root: Any


class ResourceShareInvitationExpiredException(RootModel[Any]):
    root: Any


class ResourceShareInvitationStatus(Enum):
    PENDING = 'PENDING'
    ACCEPTED = 'ACCEPTED'
    REJECTED = 'REJECTED'
    EXPIRED = 'EXPIRED'


class ResourceShareLimitExceededException(RootModel[Any]):
    root: Any


class ResourceShareStatus(Enum):
    PENDING = 'PENDING'
    ACTIVE = 'ACTIVE'
    FAILED = 'FAILED'
    DELETING = 'DELETING'
    DELETED = 'DELETED'


class ResourceStatus(Enum):
    AVAILABLE = 'AVAILABLE'
    ZONAL_RESOURCE_INACCESSIBLE = 'ZONAL_RESOURCE_INACCESSIBLE'
    LIMIT_EXCEEDED = 'LIMIT_EXCEEDED'
    UNAVAILABLE = 'UNAVAILABLE'
    PENDING = 'PENDING'


class ServerInternalException(RootModel[Any]):
    root: Any


class ServiceUnavailableException(RootModel[Any]):
    root: Any


class String(RootModel[str]):
    root: str


class TagKey(RootModel[str]):
    root: str


class TagKeyList(RootModel[List[TagKey]]):
    root: List[TagKey]


class TagLimitExceededException(RootModel[Any]):
    root: Any


class TagPolicyViolationException(RootModel[Any]):
    root: Any


class TagResourceResponse(BaseModel):
    pass


class TagValue(RootModel[str]):
    root: str


class TagValueList(RootModel[List[TagValue]]):
    root: List[TagValue]


class ThrottlingException(RootModel[Any]):
    root: Any


class UnknownResourceException(RootModel[Any]):
    root: Any


class UnmatchedPolicyPermissionException(RootModel[Any]):
    root: Any


class UntagResourceRequest(BaseModel):
    resourceArn: Optional[String] = None
    resourceShareArn: Optional[String] = None
    tagKeys: TagKeyList


class UntagResourceResponse(BaseModel):
    pass


class UpdateResourceShareRequest(BaseModel):
    allowExternalPrincipals: Optional[Boolean] = None
    clientToken: Optional[String] = None
    name: Optional[String] = None
    resourceShareArn: String


class AcceptresourceshareinvitationPostRequest(BaseModel):
    clientToken: Optional[str] = Field(
        None,
        description='<p>Specifies a unique, case-sensitive identifier that you provide to ensure the idempotency of the request. This lets you safely retry the request without accidentally performing the same operation a second time. Passing the same value to a later call to an operation requires that you also pass the same value for all other parameters. We recommend that you use a <a href="https://wikipedia.org/wiki/Universally_unique_identifier">UUID type of value.</a>.</p> <p>If you don\'t provide this value, then Amazon Web Services generates a random one for you.</p> <p>If you retry the operation with the same <code>ClientToken</code>, but with different parameters, the retry fails with an <code>IdempotentParameterMismatch</code> error.</p>',
    )
    resourceShareInvitationArn: str = Field(
        ...,
        description='The <a href="https://docs.aws.amazon.com/general/latest/gr/aws-arns-and-namespaces.html">Amazon Resource Name (ARN)</a> of the invitation that you want to accept.',
    )


class AssociateresourcesharePostRequest(BaseModel):
    clientToken: Optional[str] = Field(
        None,
        description='<p>Specifies a unique, case-sensitive identifier that you provide to ensure the idempotency of the request. This lets you safely retry the request without accidentally performing the same operation a second time. Passing the same value to a later call to an operation requires that you also pass the same value for all other parameters. We recommend that you use a <a href="https://wikipedia.org/wiki/Universally_unique_identifier">UUID type of value.</a>.</p> <p>If you don\'t provide this value, then Amazon Web Services generates a random one for you.</p> <p>If you retry the operation with the same <code>ClientToken</code>, but with different parameters, the retry fails with an <code>IdempotentParameterMismatch</code> error.</p>',
    )
    principals: Optional[List[String]] = Field(
        None,
        description='<p>Specifies a list of principals to whom you want to the resource share. This can be <code>null</code> if you want to add only resources.</p> <p>What the principals can do with the resources in the share is determined by the RAM permissions that you associate with the resource share. See <a>AssociateResourceSharePermission</a>.</p> <p>You can include the following values:</p> <ul> <li> <p>An Amazon Web Services account ID, for example: <code>123456789012</code> </p> </li> <li> <p>An <a href="https://docs.aws.amazon.com/general/latest/gr/aws-arns-and-namespaces.html">Amazon Resource Name (ARN)</a> of an organization in Organizations, for example: <code>organizations::123456789012:organization/o-exampleorgid</code> </p> </li> <li> <p>An ARN of an organizational unit (OU) in Organizations, for example: <code>organizations::123456789012:ou/o-exampleorgid/ou-examplerootid-exampleouid123</code> </p> </li> <li> <p>An ARN of an IAM role, for example: <code>iam::123456789012:role/rolename</code> </p> </li> <li> <p>An ARN of an IAM user, for example: <code>iam::123456789012user/username</code> </p> </li> </ul> <note> <p>Not all resource types can be shared with IAM roles and users. For more information, see <a href="https://docs.aws.amazon.com/ram/latest/userguide/permissions.html#permissions-rbp-supported-resource-types">Sharing with IAM roles and users</a> in the <i>Resource Access Manager User Guide</i>.</p> </note>',
    )
    resourceArns: Optional[List[String]] = Field(
        None,
        description='Specifies a list of <a href="https://docs.aws.amazon.com/general/latest/gr/aws-arns-and-namespaces.html">Amazon Resource Names (ARNs)</a> of the resources that you want to share. This can be <code>null</code> if you want to add only principals.',
    )
    resourceShareArn: str = Field(
        ...,
        description='Specifies the <a href="https://docs.aws.amazon.com/general/latest/gr/aws-arns-and-namespaces.html">Amazon Resource Name (ARN)</a> of the resource share that you want to add principals or resources to.',
    )


class AssociateresourcesharepermissionPostRequest(BaseModel):
    clientToken: Optional[str] = Field(
        None,
        description='<p>Specifies a unique, case-sensitive identifier that you provide to ensure the idempotency of the request. This lets you safely retry the request without accidentally performing the same operation a second time. Passing the same value to a later call to an operation requires that you also pass the same value for all other parameters. We recommend that you use a <a href="https://wikipedia.org/wiki/Universally_unique_identifier">UUID type of value.</a>.</p> <p>If you don\'t provide this value, then Amazon Web Services generates a random one for you.</p> <p>If you retry the operation with the same <code>ClientToken</code>, but with different parameters, the retry fails with an <code>IdempotentParameterMismatch</code> error.</p>',
    )
    permissionArn: str = Field(
        ...,
        description='Specifies the <a href="https://docs.aws.amazon.com/general/latest/gr/aws-arns-and-namespaces.html">Amazon Resource Name (ARN)</a> of the RAM permission to associate with the resource share. To find the ARN for a permission, use either the <a>ListPermissions</a> operation or go to the <a href="https://console.aws.amazon.com/ram/home#Permissions:">Permissions library</a> page in the RAM console and then choose the name of the permission. The ARN is displayed on the detail page.',
    )
    permissionVersion: Optional[int] = Field(
        None,
        description="<p>Specifies the version of the RAM permission to associate with the resource share. You can specify <i>only</i> the version that is currently set as the default version for the permission. If you also set the <code>replace</code> pararameter to <code>true</code>, then this operation updates an outdated version of the permission to the current default version.</p> <note> <p>You don't need to specify this parameter because the default behavior is to use the version that is currently set as the default version for the permission. This parameter is supported for backwards compatibility.</p> </note>",
    )
    replace: Optional[bool] = Field(
        None,
        description="<p>Specifies whether the specified permission should replace the existing permission associated with the resource share. Use <code>true</code> to replace the current permissions. Use <code>false</code> to add the permission to a resource share that currently doesn't have a permission. The default value is <code>false</code>.</p> <note> <p>A resource share can have only one permission per resource type. If a resource share already has a permission for the specified resource type and you don't set <code>replace</code> to <code>true</code> then the operation returns an error. This helps prevent accidental overwriting of a permission.</p> </note>",
    )
    resourceShareArn: str = Field(
        ...,
        description='Specifies the <a href="https://docs.aws.amazon.com/general/latest/gr/aws-arns-and-namespaces.html">Amazon Resource Name (ARN)</a> of the resource share to which you want to add or replace permissions.',
    )


class CreatepermissionversionPostRequest(BaseModel):
    clientToken: Optional[str] = Field(
        None,
        description='<p>Specifies a unique, case-sensitive identifier that you provide to ensure the idempotency of the request. This lets you safely retry the request without accidentally performing the same operation a second time. Passing the same value to a later call to an operation requires that you also pass the same value for all other parameters. We recommend that you use a <a href="https://wikipedia.org/wiki/Universally_unique_identifier">UUID type of value.</a>.</p> <p>If you don\'t provide this value, then Amazon Web Services generates a random one for you.</p> <p>If you retry the operation with the same <code>ClientToken</code>, but with different parameters, the retry fails with an <code>IdempotentParameterMismatch</code> error.</p>',
    )
    permissionArn: str = Field(
        ...,
        description='Specifies the <a href="https://docs.aws.amazon.com/general/latest/gr/aws-arns-and-namespaces.html">Amazon Resource Name (ARN)</a> of the customer managed permission you\'re creating a new version for.',
    )
    policyTemplate: str = Field(
        ...,
        description='<p>A string in JSON format string that contains the following elements of a resource-based policy:</p> <ul> <li> <p> <b>Effect</b>: must be set to <code>ALLOW</code>.</p> </li> <li> <p> <b>Action</b>: specifies the actions that are allowed by this customer managed permission. The list must contain only actions that are supported by the specified resource type. For a list of all actions supported by each resource type, see <a href="https://docs.aws.amazon.com/service-authorization/latest/reference/reference_policies_actions-resources-contextkeys.html">Actions, resources, and condition keys for Amazon Web Services services</a> in the <i>Identity and Access Management User Guide</i>.</p> </li> <li> <p> <b>Condition</b>: (optional) specifies conditional parameters that must evaluate to true when a user attempts an action for that action to be allowed. For more information about the Condition element, see <a href="https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_elements_condition.html">IAM policies: Condition element</a> in the <i>Identity and Access Management User Guide</i>.</p> </li> </ul> <p>This template can\'t include either the <code>Resource</code> or <code>Principal</code> elements. Those are both filled in by RAM when it instantiates the resource-based policy on each resource shared using this managed permission. The <code>Resource</code> comes from the ARN of the specific resource that you are sharing. The <code>Principal</code> comes from the list of identities added to the resource share.</p>',
    )


class DisassociateresourcesharePostRequest(BaseModel):
    clientToken: Optional[str] = Field(
        None,
        description='<p>Specifies a unique, case-sensitive identifier that you provide to ensure the idempotency of the request. This lets you safely retry the request without accidentally performing the same operation a second time. Passing the same value to a later call to an operation requires that you also pass the same value for all other parameters. We recommend that you use a <a href="https://wikipedia.org/wiki/Universally_unique_identifier">UUID type of value.</a>.</p> <p>If you don\'t provide this value, then Amazon Web Services generates a random one for you.</p> <p>If you retry the operation with the same <code>ClientToken</code>, but with different parameters, the retry fails with an <code>IdempotentParameterMismatch</code> error.</p>',
    )
    principals: Optional[List[String]] = Field(
        None,
        description='<p>Specifies a list of one or more principals that no longer are to have access to the resources in this resource share.</p> <p>You can include the following values:</p> <ul> <li> <p>An Amazon Web Services account ID, for example: <code>123456789012</code> </p> </li> <li> <p>An <a href="https://docs.aws.amazon.com/general/latest/gr/aws-arns-and-namespaces.html">Amazon Resource Name (ARN)</a> of an organization in Organizations, for example: <code>organizations::123456789012:organization/o-exampleorgid</code> </p> </li> <li> <p>An ARN of an organizational unit (OU) in Organizations, for example: <code>organizations::123456789012:ou/o-exampleorgid/ou-examplerootid-exampleouid123</code> </p> </li> <li> <p>An ARN of an IAM role, for example: <code>iam::123456789012:role/rolename</code> </p> </li> <li> <p>An ARN of an IAM user, for example: <code>iam::123456789012user/username</code> </p> </li> </ul> <note> <p>Not all resource types can be shared with IAM roles and users. For more information, see <a href="https://docs.aws.amazon.com/ram/latest/userguide/permissions.html#permissions-rbp-supported-resource-types">Sharing with IAM roles and users</a> in the <i>Resource Access Manager User Guide</i>.</p> </note>',
    )
    resourceArns: Optional[List[String]] = Field(
        None,
        description='Specifies a list of <a href="https://docs.aws.amazon.com/general/latest/gr/aws-arns-and-namespaces.html">Amazon Resource Names (ARNs)</a> for one or more resources that you want to remove from the resource share. After the operation runs, these resources are no longer shared with principals associated with the resource share.',
    )
    resourceShareArn: str = Field(
        ...,
        description='Specifies <a href="https://docs.aws.amazon.com/general/latest/gr/aws-arns-and-namespaces.html">Amazon Resource Name (ARN)</a> of the resource share that you want to remove resources or principals from.',
    )


class DisassociateresourcesharepermissionPostRequest(BaseModel):
    clientToken: Optional[str] = Field(
        None,
        description='<p>Specifies a unique, case-sensitive identifier that you provide to ensure the idempotency of the request. This lets you safely retry the request without accidentally performing the same operation a second time. Passing the same value to a later call to an operation requires that you also pass the same value for all other parameters. We recommend that you use a <a href="https://wikipedia.org/wiki/Universally_unique_identifier">UUID type of value.</a>.</p> <p>If you don\'t provide this value, then Amazon Web Services generates a random one for you.</p> <p>If you retry the operation with the same <code>ClientToken</code>, but with different parameters, the retry fails with an <code>IdempotentParameterMismatch</code> error.</p>',
    )
    permissionArn: str = Field(
        ...,
        description='The <a href="https://docs.aws.amazon.com/general/latest/gr/aws-arns-and-namespaces.html">Amazon Resource Name (ARN)</a> of the managed permission to disassociate from the resource share. Changes to permissions take effect immediately.',
    )
    resourceShareArn: str = Field(
        ...,
        description='The <a href="https://docs.aws.amazon.com/general/latest/gr/aws-arns-and-namespaces.html">Amazon Resource Name (ARN)</a> of the resource share that you want to remove the managed permission from.',
    )


class GetpermissionPostRequest(BaseModel):
    permissionArn: str = Field(
        ...,
        description='Specifies the <a href="https://docs.aws.amazon.com/general/latest/gr/aws-arns-and-namespaces.html">Amazon Resource Name (ARN)</a> of the permission whose contents you want to retrieve. To find the ARN for a permission, use either the <a>ListPermissions</a> operation or go to the <a href="https://console.aws.amazon.com/ram/home#Permissions:">Permissions library</a> page in the RAM console and then choose the name of the permission. The ARN is displayed on the detail page.',
    )
    permissionVersion: Optional[int] = Field(
        None,
        description="<p>Specifies the version number of the RAM permission to retrieve. If you don't specify this parameter, the operation retrieves the default version.</p> <p>To see the list of available versions, use <a>ListPermissionVersions</a>.</p>",
    )


class GetresourcepoliciesPostRequest(BaseModel):
    maxResults: Optional[conint(ge=1, le=500)] = Field(
        None,
        description='Specifies the total number of results that you want included on each page of the response. If you do not include this parameter, it defaults to a value that is specific to the operation. If additional items exist beyond the number you specify, the <code>NextToken</code> response element is returned with a value (not null). Include the specified value as the <code>NextToken</code> request parameter in the next call to the operation to get the next part of the results. Note that the service might return fewer results than the maximum even when there are more results available. You should check <code>NextToken</code> after every operation to ensure that you receive all of the results.',
    )
    nextToken: Optional[str] = Field(
        None,
        description="Specifies that you want to receive the next page of results. Valid only if you received a <code>NextToken</code> response in the previous request. If you did, it indicates that more output is available. Set this parameter to the value provided by the previous call's <code>NextToken</code> response to request the next page of results.",
    )
    principal: Optional[str] = Field(None, description='Specifies the principal.')
    resourceArns: List[String] = Field(
        ...,
        description='Specifies the <a href="https://docs.aws.amazon.com/general/latest/gr/aws-arns-and-namespaces.html">Amazon Resource Names (ARNs)</a> of the resources whose policies you want to retrieve.',
    )


class AssociationStatus(Enum):
    ASSOCIATING = 'ASSOCIATING'
    ASSOCIATED = 'ASSOCIATED'
    FAILED = 'FAILED'
    DISASSOCIATING = 'DISASSOCIATING'
    DISASSOCIATED = 'DISASSOCIATED'


class AssociationType(Enum):
    PRINCIPAL = 'PRINCIPAL'
    RESOURCE = 'RESOURCE'


class GetresourceshareassociationsPostRequest(BaseModel):
    associationStatus: Optional[AssociationStatus] = Field(
        None,
        description='Specifies that you want to retrieve only associations that have this status.',
    )
    associationType: AssociationType = Field(
        ...,
        description='<p>Specifies whether you want to retrieve the associations that involve a specified resource or principal.</p> <ul> <li> <p> <code>PRINCIPAL</code> – list the principals whose associations you want to see.</p> </li> <li> <p> <code>RESOURCE</code> – list the resources whose associations you want to see.</p> </li> </ul>',
    )
    maxResults: Optional[conint(ge=1, le=500)] = Field(
        None,
        description='Specifies the total number of results that you want included on each page of the response. If you do not include this parameter, it defaults to a value that is specific to the operation. If additional items exist beyond the number you specify, the <code>NextToken</code> response element is returned with a value (not null). Include the specified value as the <code>NextToken</code> request parameter in the next call to the operation to get the next part of the results. Note that the service might return fewer results than the maximum even when there are more results available. You should check <code>NextToken</code> after every operation to ensure that you receive all of the results.',
    )
    nextToken: Optional[str] = Field(
        None,
        description="Specifies that you want to receive the next page of results. Valid only if you received a <code>NextToken</code> response in the previous request. If you did, it indicates that more output is available. Set this parameter to the value provided by the previous call's <code>NextToken</code> response to request the next page of results.",
    )
    principal: Optional[str] = Field(
        None,
        description='<p>Specifies the ID of the principal whose resource shares you want to retrieve. This can be an Amazon Web Services account ID, an organization ID, an organizational unit ID, or the <a href="https://docs.aws.amazon.com/general/latest/gr/aws-arns-and-namespaces.html">Amazon Resource Name (ARN)</a> of an individual IAM user or role.</p> <p>You cannot specify this parameter if the association type is <code>RESOURCE</code>.</p>',
    )
    resourceArn: Optional[str] = Field(
        None,
        description='<p>Specifies the <a href="https://docs.aws.amazon.com/general/latest/gr/aws-arns-and-namespaces.html">Amazon Resource Name (ARN)</a> of a resource whose resource shares you want to retrieve.</p> <p>You cannot specify this parameter if the association type is <code>PRINCIPAL</code>.</p>',
    )
    resourceShareArns: Optional[List[String]] = Field(
        None,
        description='Specifies a list of <a href="https://docs.aws.amazon.com/general/latest/gr/aws-arns-and-namespaces.html">Amazon Resource Names (ARNs)</a> of the resource share whose associations you want to retrieve.',
    )


class GetresourceshareinvitationsPostRequest(BaseModel):
    maxResults: Optional[conint(ge=1, le=500)] = Field(
        None,
        description='Specifies the total number of results that you want included on each page of the response. If you do not include this parameter, it defaults to a value that is specific to the operation. If additional items exist beyond the number you specify, the <code>NextToken</code> response element is returned with a value (not null). Include the specified value as the <code>NextToken</code> request parameter in the next call to the operation to get the next part of the results. Note that the service might return fewer results than the maximum even when there are more results available. You should check <code>NextToken</code> after every operation to ensure that you receive all of the results.',
    )
    nextToken: Optional[str] = Field(
        None,
        description="Specifies that you want to receive the next page of results. Valid only if you received a <code>NextToken</code> response in the previous request. If you did, it indicates that more output is available. Set this parameter to the value provided by the previous call's <code>NextToken</code> response to request the next page of results.",
    )
    resourceShareArns: Optional[List[String]] = Field(
        None,
        description='Specifies that you want details about invitations only for the resource shares described by this list of <a href="https://docs.aws.amazon.com/general/latest/gr/aws-arns-and-namespaces.html">Amazon Resource Names (ARNs)</a> ',
    )
    resourceShareInvitationArns: Optional[List[String]] = Field(
        None,
        description='Specifies the <a href="https://docs.aws.amazon.com/general/latest/gr/aws-arns-and-namespaces.html">Amazon Resource Names (ARNs)</a> of the resource share invitations you want information about.',
    )


class ResourceRegionScope1(Enum):
    ALL = 'ALL'
    REGIONAL = 'REGIONAL'
    GLOBAL = 'GLOBAL'


class ListpendinginvitationresourcesPostRequest(BaseModel):
    maxResults: Optional[conint(ge=1, le=500)] = Field(
        None,
        description='Specifies the total number of results that you want included on each page of the response. If you do not include this parameter, it defaults to a value that is specific to the operation. If additional items exist beyond the number you specify, the <code>NextToken</code> response element is returned with a value (not null). Include the specified value as the <code>NextToken</code> request parameter in the next call to the operation to get the next part of the results. Note that the service might return fewer results than the maximum even when there are more results available. You should check <code>NextToken</code> after every operation to ensure that you receive all of the results.',
    )
    nextToken: Optional[str] = Field(
        None,
        description="Specifies that you want to receive the next page of results. Valid only if you received a <code>NextToken</code> response in the previous request. If you did, it indicates that more output is available. Set this parameter to the value provided by the previous call's <code>NextToken</code> response to request the next page of results.",
    )
    resourceRegionScope: Optional[ResourceRegionScope1] = Field(
        None,
        description='<p>Specifies that you want the results to include only resources that have the specified scope.</p> <ul> <li> <p> <code>ALL</code> – the results include both global and regional resources or resource types.</p> </li> <li> <p> <code>GLOBAL</code> – the results include only global resources or resource types.</p> </li> <li> <p> <code>REGIONAL</code> – the results include only regional resources or resource types.</p> </li> </ul> <p>The default value is <code>ALL</code>.</p>',
    )
    resourceShareInvitationArn: str = Field(
        ...,
        description='Specifies the <a href="https://docs.aws.amazon.com/general/latest/gr/aws-arns-and-namespaces.html">Amazon Resource Name (ARN)</a> of the invitation. You can use <a>GetResourceShareInvitations</a> to find the ARN of the invitation.',
    )


class FeatureSet(Enum):
    CREATED_FROM_POLICY = 'CREATED_FROM_POLICY'
    PROMOTING_TO_STANDARD = 'PROMOTING_TO_STANDARD'
    STANDARD = 'STANDARD'


class ListpermissionassociationsPostRequest(BaseModel):
    associationStatus: Optional[AssociationStatus] = Field(
        None,
        description='Specifies that you want to list only those associations with resource shares that match this status.',
    )
    defaultVersion: Optional[bool] = Field(
        None,
        description='<p>When <code>true</code>, specifies that you want to list only those associations with resource shares that use the default version of the specified managed permission.</p> <p>When <code>false</code> (the default value), lists associations with resource shares that use any version of the specified managed permission.</p>',
    )
    featureSet: Optional[FeatureSet] = Field(
        None,
        description='Specifies that you want to list only those associations with resource shares that have a <code>featureSet</code> with this value.',
    )
    maxResults: Optional[conint(ge=1, le=500)] = Field(
        None,
        description='Specifies the total number of results that you want included on each page of the response. If you do not include this parameter, it defaults to a value that is specific to the operation. If additional items exist beyond the number you specify, the <code>NextToken</code> response element is returned with a value (not null). Include the specified value as the <code>NextToken</code> request parameter in the next call to the operation to get the next part of the results. Note that the service might return fewer results than the maximum even when there are more results available. You should check <code>NextToken</code> after every operation to ensure that you receive all of the results.',
    )
    nextToken: Optional[str] = Field(
        None,
        description="Specifies that you want to receive the next page of results. Valid only if you received a <code>NextToken</code> response in the previous request. If you did, it indicates that more output is available. Set this parameter to the value provided by the previous call's <code>NextToken</code> response to request the next page of results.",
    )
    permissionArn: Optional[str] = Field(
        None,
        description='Specifies the <a href="https://docs.aws.amazon.com/general/latest/gr/aws-arns-and-namespaces.html">Amazon Resource Name (ARN)</a> of the managed permission.',
    )
    permissionVersion: Optional[int] = Field(
        None,
        description="Specifies that you want to list only those associations with resource shares that use this version of the managed permission. If you don't provide a value for this parameter, then the operation returns information about associations with resource shares that use any version of the managed permission.",
    )
    resourceType: Optional[str] = Field(
        None,
        description='Specifies that you want to list only those associations with resource shares that include at least one resource of this resource type.',
    )


class PermissionType1(Enum):
    ALL = 'ALL'
    AWS_MANAGED = 'AWS_MANAGED'
    CUSTOMER_MANAGED = 'CUSTOMER_MANAGED'


class ListpermissionsPostRequest(BaseModel):
    maxResults: Optional[conint(ge=1, le=500)] = Field(
        None,
        description='Specifies the total number of results that you want included on each page of the response. If you do not include this parameter, it defaults to a value that is specific to the operation. If additional items exist beyond the number you specify, the <code>NextToken</code> response element is returned with a value (not null). Include the specified value as the <code>NextToken</code> request parameter in the next call to the operation to get the next part of the results. Note that the service might return fewer results than the maximum even when there are more results available. You should check <code>NextToken</code> after every operation to ensure that you receive all of the results.',
    )
    nextToken: Optional[str] = Field(
        None,
        description="Specifies that you want to receive the next page of results. Valid only if you received a <code>NextToken</code> response in the previous request. If you did, it indicates that more output is available. Set this parameter to the value provided by the previous call's <code>NextToken</code> response to request the next page of results.",
    )
    permissionType: Optional[PermissionType1] = Field(
        None,
        description="<p>Specifies that you want to list only permissions of this type:</p> <ul> <li> <p> <code>AWS</code> – returns only Amazon Web Services managed permissions.</p> </li> <li> <p> <code>LOCAL</code> – returns only customer managed permissions</p> </li> <li> <p> <code>ALL</code> – returns both Amazon Web Services managed permissions and customer managed permissions.</p> </li> </ul> <p>If you don't specify this parameter, the default is <code>All</code>.</p>",
    )
    resourceType: Optional[str] = Field(
        None,
        description='<p>Specifies that you want to list only those permissions that apply to the specified resource type. This parameter is not case sensitive.</p> <p>For example, to list only permissions that apply to Amazon EC2 subnets, specify <code>ec2:subnet</code>. You can use the <a>ListResourceTypes</a> operation to get the specific string required.</p>',
    )


class ListpermissionversionsPostRequest(BaseModel):
    maxResults: Optional[conint(ge=1, le=500)] = Field(
        None,
        description='Specifies the total number of results that you want included on each page of the response. If you do not include this parameter, it defaults to a value that is specific to the operation. If additional items exist beyond the number you specify, the <code>NextToken</code> response element is returned with a value (not null). Include the specified value as the <code>NextToken</code> request parameter in the next call to the operation to get the next part of the results. Note that the service might return fewer results than the maximum even when there are more results available. You should check <code>NextToken</code> after every operation to ensure that you receive all of the results.',
    )
    nextToken: Optional[str] = Field(
        None,
        description="Specifies that you want to receive the next page of results. Valid only if you received a <code>NextToken</code> response in the previous request. If you did, it indicates that more output is available. Set this parameter to the value provided by the previous call's <code>NextToken</code> response to request the next page of results.",
    )
    permissionArn: str = Field(
        ...,
        description='Specifies the <a href="https://docs.aws.amazon.com/general/latest/gr/aws-arns-and-namespaces.html">Amazon Resource Name (ARN)</a> of the RAM permission whose versions you want to list. You can use the <code>permissionVersion</code> parameter on the <a>AssociateResourceSharePermission</a> operation to specify a non-default version to attach.',
    )


class ListprincipalsPostRequest(BaseModel):
    maxResults: Optional[conint(ge=1, le=500)] = Field(
        None,
        description='Specifies the total number of results that you want included on each page of the response. If you do not include this parameter, it defaults to a value that is specific to the operation. If additional items exist beyond the number you specify, the <code>NextToken</code> response element is returned with a value (not null). Include the specified value as the <code>NextToken</code> request parameter in the next call to the operation to get the next part of the results. Note that the service might return fewer results than the maximum even when there are more results available. You should check <code>NextToken</code> after every operation to ensure that you receive all of the results.',
    )
    nextToken: Optional[str] = Field(
        None,
        description="Specifies that you want to receive the next page of results. Valid only if you received a <code>NextToken</code> response in the previous request. If you did, it indicates that more output is available. Set this parameter to the value provided by the previous call's <code>NextToken</code> response to request the next page of results.",
    )
    principals: Optional[List[String]] = Field(
        None,
        description='<p>Specifies that you want to list information for only the listed principals.</p> <p>You can include the following values:</p> <ul> <li> <p>An Amazon Web Services account ID, for example: <code>123456789012</code> </p> </li> <li> <p>An <a href="https://docs.aws.amazon.com/general/latest/gr/aws-arns-and-namespaces.html">Amazon Resource Name (ARN)</a> of an organization in Organizations, for example: <code>organizations::123456789012:organization/o-exampleorgid</code> </p> </li> <li> <p>An ARN of an organizational unit (OU) in Organizations, for example: <code>organizations::123456789012:ou/o-exampleorgid/ou-examplerootid-exampleouid123</code> </p> </li> <li> <p>An ARN of an IAM role, for example: <code>iam::123456789012:role/rolename</code> </p> </li> <li> <p>An ARN of an IAM user, for example: <code>iam::123456789012user/username</code> </p> </li> </ul> <note> <p>Not all resource types can be shared with IAM roles and users. For more information, see <a href="https://docs.aws.amazon.com/ram/latest/userguide/permissions.html#permissions-rbp-supported-resource-types">Sharing with IAM roles and users</a> in the <i>Resource Access Manager User Guide</i>.</p> </note>',
    )
    resourceArn: Optional[str] = Field(
        None,
        description='Specifies that you want to list principal information for the resource share with the specified <a href="https://docs.aws.amazon.com/general/latest/gr/aws-arns-and-namespaces.html">Amazon Resource Name (ARN)</a>.',
    )
    resourceOwner: ResourceOwner = Field(
        ...,
        description='<p>Specifies that you want to list information for only resource shares that match the following:</p> <ul> <li> <p> <b> <code>SELF</code> </b> – principals that your account is sharing resources with</p> </li> <li> <p> <b> <code>OTHER-ACCOUNTS</code> </b> – principals that are sharing resources with your account</p> </li> </ul>',
    )
    resourceShareArns: Optional[List[String]] = Field(
        None,
        description='Specifies that you want to list information for only principals associated with the resource shares specified by a list the <a href="https://docs.aws.amazon.com/general/latest/gr/aws-arns-and-namespaces.html">Amazon Resource Names (ARNs)</a>.',
    )
    resourceType: Optional[str] = Field(
        None,
        description='<p>Specifies that you want to list information for only principals associated with resource shares that include the specified resource type.</p> <p>For a list of valid values, query the <a>ListResourceTypes</a> operation.</p>',
    )


class Status(Enum):
    IN_PROGRESS = 'IN_PROGRESS'
    COMPLETED = 'COMPLETED'
    FAILED = 'FAILED'


class ListreplacepermissionassociationsworkPostRequest(BaseModel):
    maxResults: Optional[conint(ge=1, le=500)] = Field(
        None,
        description='Specifies the total number of results that you want included on each page of the response. If you do not include this parameter, it defaults to a value that is specific to the operation. If additional items exist beyond the number you specify, the <code>NextToken</code> response element is returned with a value (not null). Include the specified value as the <code>NextToken</code> request parameter in the next call to the operation to get the next part of the results. Note that the service might return fewer results than the maximum even when there are more results available. You should check <code>NextToken</code> after every operation to ensure that you receive all of the results.',
    )
    nextToken: Optional[str] = Field(
        None,
        description="Specifies that you want to receive the next page of results. Valid only if you received a <code>NextToken</code> response in the previous request. If you did, it indicates that more output is available. Set this parameter to the value provided by the previous call's <code>NextToken</code> response to request the next page of results.",
    )
    status: Optional[Status] = Field(
        None,
        description='Specifies that you want to see only the details about requests with a status that matches this value.',
    )
    workIds: Optional[List[String]] = Field(
        None,
        description='A list of IDs. These values come from the <code>id</code>field of the <code>replacePermissionAssociationsWork</code>structure returned by the <a>ReplacePermissionAssociations</a> operation. ',
    )


class ListresourcesPostRequest(BaseModel):
    maxResults: Optional[conint(ge=1, le=500)] = Field(
        None,
        description='Specifies the total number of results that you want included on each page of the response. If you do not include this parameter, it defaults to a value that is specific to the operation. If additional items exist beyond the number you specify, the <code>NextToken</code> response element is returned with a value (not null). Include the specified value as the <code>NextToken</code> request parameter in the next call to the operation to get the next part of the results. Note that the service might return fewer results than the maximum even when there are more results available. You should check <code>NextToken</code> after every operation to ensure that you receive all of the results.',
    )
    nextToken: Optional[str] = Field(
        None,
        description="Specifies that you want to receive the next page of results. Valid only if you received a <code>NextToken</code> response in the previous request. If you did, it indicates that more output is available. Set this parameter to the value provided by the previous call's <code>NextToken</code> response to request the next page of results.",
    )
    principal: Optional[str] = Field(
        None,
        description='Specifies that you want to list only the resource shares that are associated with the specified principal.',
    )
    resourceArns: Optional[List[String]] = Field(
        None,
        description='Specifies that you want to list only the resource shares that include resources with the specified <a href="https://docs.aws.amazon.com/general/latest/gr/aws-arns-and-namespaces.html">Amazon Resource Names (ARNs)</a>.',
    )
    resourceOwner: ResourceOwner = Field(
        ...,
        description='<p>Specifies that you want to list only the resource shares that match the following:</p> <ul> <li> <p> <b> <code>SELF</code> </b> – resources that your account shares with other accounts</p> </li> <li> <p> <b> <code>OTHER-ACCOUNTS</code> </b> – resources that other accounts share with your account</p> </li> </ul>',
    )
    resourceRegionScope: Optional[ResourceRegionScope1] = Field(
        None,
        description='<p>Specifies that you want the results to include only resources that have the specified scope.</p> <ul> <li> <p> <code>ALL</code> – the results include both global and regional resources or resource types.</p> </li> <li> <p> <code>GLOBAL</code> – the results include only global resources or resource types.</p> </li> <li> <p> <code>REGIONAL</code> – the results include only regional resources or resource types.</p> </li> </ul> <p>The default value is <code>ALL</code>.</p>',
    )
    resourceShareArns: Optional[List[String]] = Field(
        None,
        description='Specifies that you want to list only resources in the resource shares identified by the specified <a href="https://docs.aws.amazon.com/general/latest/gr/aws-arns-and-namespaces.html">Amazon Resource Names (ARNs)</a>.',
    )
    resourceType: Optional[str] = Field(
        None,
        description='<p>Specifies that you want to list only the resource shares that include resources of the specified resource type.</p> <p>For valid values, query the <a>ListResourceTypes</a> operation.</p>',
    )


class ListresourcesharepermissionsPostRequest(BaseModel):
    maxResults: Optional[conint(ge=1, le=500)] = Field(
        None,
        description='Specifies the total number of results that you want included on each page of the response. If you do not include this parameter, it defaults to a value that is specific to the operation. If additional items exist beyond the number you specify, the <code>NextToken</code> response element is returned with a value (not null). Include the specified value as the <code>NextToken</code> request parameter in the next call to the operation to get the next part of the results. Note that the service might return fewer results than the maximum even when there are more results available. You should check <code>NextToken</code> after every operation to ensure that you receive all of the results.',
    )
    nextToken: Optional[str] = Field(
        None,
        description="Specifies that you want to receive the next page of results. Valid only if you received a <code>NextToken</code> response in the previous request. If you did, it indicates that more output is available. Set this parameter to the value provided by the previous call's <code>NextToken</code> response to request the next page of results.",
    )
    resourceShareArn: str = Field(
        ...,
        description='Specifies the <a href="https://docs.aws.amazon.com/general/latest/gr/aws-arns-and-namespaces.html">Amazon Resource Name (ARN)</a> of the resource share for which you want to retrieve the associated permissions.',
    )


class ListresourcetypesPostRequest(BaseModel):
    maxResults: Optional[conint(ge=1, le=500)] = Field(
        None,
        description='Specifies the total number of results that you want included on each page of the response. If you do not include this parameter, it defaults to a value that is specific to the operation. If additional items exist beyond the number you specify, the <code>NextToken</code> response element is returned with a value (not null). Include the specified value as the <code>NextToken</code> request parameter in the next call to the operation to get the next part of the results. Note that the service might return fewer results than the maximum even when there are more results available. You should check <code>NextToken</code> after every operation to ensure that you receive all of the results.',
    )
    nextToken: Optional[str] = Field(
        None,
        description="Specifies that you want to receive the next page of results. Valid only if you received a <code>NextToken</code> response in the previous request. If you did, it indicates that more output is available. Set this parameter to the value provided by the previous call's <code>NextToken</code> response to request the next page of results.",
    )
    resourceRegionScope: Optional[ResourceRegionScope1] = Field(
        None,
        description='<p>Specifies that you want the results to include only resources that have the specified scope.</p> <ul> <li> <p> <code>ALL</code> – the results include both global and regional resources or resource types.</p> </li> <li> <p> <code>GLOBAL</code> – the results include only global resources or resource types.</p> </li> <li> <p> <code>REGIONAL</code> – the results include only regional resources or resource types.</p> </li> </ul> <p>The default value is <code>ALL</code>.</p>',
    )


class PromotepermissioncreatedfrompolicyPostRequest(BaseModel):
    clientToken: Optional[str] = Field(
        None,
        description='<p>Specifies a unique, case-sensitive identifier that you provide to ensure the idempotency of the request. This lets you safely retry the request without accidentally performing the same operation a second time. Passing the same value to a later call to an operation requires that you also pass the same value for all other parameters. We recommend that you use a <a href="https://wikipedia.org/wiki/Universally_unique_identifier">UUID type of value.</a>.</p> <p>If you don\'t provide this value, then Amazon Web Services generates a random one for you.</p> <p>If you retry the operation with the same <code>ClientToken</code>, but with different parameters, the retry fails with an <code>IdempotentParameterMismatch</code> error.</p>',
    )
    name: str = Field(
        ...,
        description='Specifies a name for the promoted customer managed permission.',
    )
    permissionArn: str = Field(
        ...,
        description='Specifies the <a href="https://docs.aws.amazon.com/general/latest/gr/aws-arns-and-namespaces.html">Amazon Resource Name (ARN)</a> of the <code>CREATED_FROM_POLICY</code> permission that you want to promote. You can get this <a href="https://docs.aws.amazon.com/general/latest/gr/aws-arns-and-namespaces.html">Amazon Resource Name (ARN)</a> by calling the <a>ListResourceSharePermissions</a> operation.',
    )


class RejectresourceshareinvitationPostRequest(BaseModel):
    clientToken: Optional[str] = Field(
        None,
        description='<p>Specifies a unique, case-sensitive identifier that you provide to ensure the idempotency of the request. This lets you safely retry the request without accidentally performing the same operation a second time. Passing the same value to a later call to an operation requires that you also pass the same value for all other parameters. We recommend that you use a <a href="https://wikipedia.org/wiki/Universally_unique_identifier">UUID type of value.</a>.</p> <p>If you don\'t provide this value, then Amazon Web Services generates a random one for you.</p> <p>If you retry the operation with the same <code>ClientToken</code>, but with different parameters, the retry fails with an <code>IdempotentParameterMismatch</code> error.</p>',
    )
    resourceShareInvitationArn: str = Field(
        ...,
        description='Specifies the <a href="https://docs.aws.amazon.com/general/latest/gr/aws-arns-and-namespaces.html">Amazon Resource Name (ARN)</a> of the invitation that you want to reject.',
    )


class ReplacepermissionassociationsPostRequest(BaseModel):
    clientToken: Optional[str] = Field(
        None,
        description='<p>Specifies a unique, case-sensitive identifier that you provide to ensure the idempotency of the request. This lets you safely retry the request without accidentally performing the same operation a second time. Passing the same value to a later call to an operation requires that you also pass the same value for all other parameters. We recommend that you use a <a href="https://wikipedia.org/wiki/Universally_unique_identifier">UUID type of value.</a>.</p> <p>If you don\'t provide this value, then Amazon Web Services generates a random one for you.</p> <p>If you retry the operation with the same <code>ClientToken</code>, but with different parameters, the retry fails with an <code>IdempotentParameterMismatch</code> error.</p>',
    )
    fromPermissionArn: str = Field(
        ...,
        description='Specifies the <a href="https://docs.aws.amazon.com/general/latest/gr/aws-arns-and-namespaces.html">Amazon Resource Name (ARN)</a> of the managed permission that you want to replace.',
    )
    fromPermissionVersion: Optional[int] = Field(
        None,
        description='Specifies that you want to updated the permissions for only those resource shares that use the specified version of the managed permission.',
    )
    toPermissionArn: str = Field(
        ...,
        description='<p>Specifies the ARN of the managed permission that you want to associate with resource shares in place of the one specified by <code>fromPerssionArn</code> and <code>fromPermissionVersion</code>.</p> <p>The operation always associates the version that is currently the default for the specified managed permission.</p>',
    )


class SetdefaultpermissionversionPostRequest(BaseModel):
    clientToken: Optional[str] = Field(
        None,
        description='<p>Specifies a unique, case-sensitive identifier that you provide to ensure the idempotency of the request. This lets you safely retry the request without accidentally performing the same operation a second time. Passing the same value to a later call to an operation requires that you also pass the same value for all other parameters. We recommend that you use a <a href="https://wikipedia.org/wiki/Universally_unique_identifier">UUID type of value.</a>.</p> <p>If you don\'t provide this value, then Amazon Web Services generates a random one for you.</p> <p>If you retry the operation with the same <code>ClientToken</code>, but with different parameters, the retry fails with an <code>IdempotentParameterMismatch</code> error.</p>',
    )
    permissionArn: str = Field(
        ...,
        description='Specifies the <a href="https://docs.aws.amazon.com/general/latest/gr/aws-arns-and-namespaces.html">Amazon Resource Name (ARN)</a> of the customer managed permission whose default version you want to change.',
    )
    permissionVersion: int = Field(
        ...,
        description='Specifies the version number that you want to designate as the default for customer managed permission. To see a list of all available version numbers, use <a>ListPermissionVersions</a>.',
    )


class UntagresourcePostRequest(BaseModel):
    resourceArn: Optional[str] = Field(
        None,
        description='Specifies the <a href="https://docs.aws.amazon.com/general/latest/gr/aws-arns-and-namespaces.html">Amazon Resource Name (ARN)</a> of the managed permission that you want to remove tags from. You must specify either <code>resourceArn</code>, or <code>resourceShareArn</code>, but not both.',
    )
    resourceShareArn: Optional[str] = Field(
        None,
        description='Specifies the <a href="https://docs.aws.amazon.com/general/latest/gr/aws-arns-and-namespaces.html">Amazon Resource Name (ARN)</a> of the resource share that you want to remove tags from. The tags are removed from the resource share, not the resources in the resource share. You must specify either <code>resourceShareArn</code>, or <code>resourceArn</code>, but not both.',
    )
    tagKeys: List[TagKey] = Field(
        ...,
        description='Specifies a list of one or more tag keys that you want to remove.',
    )


class UpdateresourcesharePostRequest(BaseModel):
    allowExternalPrincipals: Optional[bool] = Field(
        None,
        description='Specifies whether principals outside your organization in Organizations can be associated with a resource share.',
    )
    clientToken: Optional[str] = Field(
        None,
        description='<p>Specifies a unique, case-sensitive identifier that you provide to ensure the idempotency of the request. This lets you safely retry the request without accidentally performing the same operation a second time. Passing the same value to a later call to an operation requires that you also pass the same value for all other parameters. We recommend that you use a <a href="https://wikipedia.org/wiki/Universally_unique_identifier">UUID type of value.</a>.</p> <p>If you don\'t provide this value, then Amazon Web Services generates a random one for you.</p> <p>If you retry the operation with the same <code>ClientToken</code>, but with different parameters, the retry fails with an <code>IdempotentParameterMismatch</code> error.</p>',
    )
    name: Optional[str] = Field(
        None,
        description='If specified, the new name that you want to attach to the resource share.',
    )
    resourceShareArn: str = Field(
        ...,
        description='Specifies the <a href="https://docs.aws.amazon.com/general/latest/gr/aws-arns-and-namespaces.html">Amazon Resource Name (ARN)</a> of the resource share that you want to modify.',
    )


class AcceptResourceShareInvitationRequest(BaseModel):
    clientToken: Optional[String] = None
    resourceShareInvitationArn: String


class AssociateResourceSharePermissionRequest(BaseModel):
    clientToken: Optional[String] = None
    permissionArn: String
    permissionVersion: Optional[Integer] = None
    replace: Optional[Boolean] = None
    resourceShareArn: String


class AssociateResourceSharePermissionResponse(BaseModel):
    clientToken: Optional[String] = None
    returnValue: Optional[Boolean] = None


class AssociatedPermission(BaseModel):
    arn: Optional[String] = None
    defaultVersion: Optional[Boolean] = None
    featureSet: Optional[PermissionFeatureSet] = None
    lastUpdatedTime: Optional[DateTime] = None
    permissionVersion: Optional[String] = None
    resourceShareArn: Optional[String] = None
    resourceType: Optional[String] = None
    status: Optional[String] = None


class AssociatedPermissionList(RootModel[List[AssociatedPermission]]):
    root: List[AssociatedPermission]


class CreatePermissionVersionRequest(BaseModel):
    clientToken: Optional[String] = None
    permissionArn: String
    policyTemplate: Policy


class DeletePermissionResponse(BaseModel):
    clientToken: Optional[String] = None
    permissionStatus: Optional[PermissionStatus] = None
    returnValue: Optional[Boolean] = None


class DeletePermissionVersionResponse(BaseModel):
    clientToken: Optional[String] = None
    permissionStatus: Optional[PermissionStatus] = None
    returnValue: Optional[Boolean] = None


class DeleteResourceShareResponse(BaseModel):
    clientToken: Optional[String] = None
    returnValue: Optional[Boolean] = None


class DisassociateResourceSharePermissionRequest(BaseModel):
    clientToken: Optional[String] = None
    permissionArn: String
    resourceShareArn: String


class DisassociateResourceSharePermissionResponse(BaseModel):
    clientToken: Optional[String] = None
    returnValue: Optional[Boolean] = None


class GetPermissionRequest(BaseModel):
    permissionArn: String
    permissionVersion: Optional[Integer] = None


class GetResourcePoliciesResponse(BaseModel):
    nextToken: Optional[String] = None
    policies: Optional[PolicyList] = None


class ListPendingInvitationResourcesRequest(BaseModel):
    maxResults: Optional[MaxResults] = None
    nextToken: Optional[String] = None
    resourceRegionScope: Optional[ResourceRegionScopeFilter] = None
    resourceShareInvitationArn: String


class ListPermissionAssociationsRequest(BaseModel):
    associationStatus: Optional[ResourceShareAssociationStatus] = None
    defaultVersion: Optional[Boolean] = None
    featureSet: Optional[PermissionFeatureSet] = None
    maxResults: Optional[MaxResults] = None
    nextToken: Optional[String] = None
    permissionArn: Optional[String] = None
    permissionVersion: Optional[Integer] = None
    resourceType: Optional[String] = None


class ListPermissionAssociationsResponse(BaseModel):
    nextToken: Optional[String] = None
    permissions: Optional[AssociatedPermissionList] = None


class ListPermissionVersionsRequest(BaseModel):
    maxResults: Optional[MaxResults] = None
    nextToken: Optional[String] = None
    permissionArn: String


class ListPermissionsRequest(BaseModel):
    maxResults: Optional[MaxResults] = None
    nextToken: Optional[String] = None
    permissionType: Optional[PermissionTypeFilter] = None
    resourceType: Optional[String] = None


class ListResourceSharePermissionsRequest(BaseModel):
    maxResults: Optional[MaxResults] = None
    nextToken: Optional[String] = None
    resourceShareArn: String


class ListResourceTypesRequest(BaseModel):
    maxResults: Optional[MaxResults] = None
    nextToken: Optional[String] = None
    resourceRegionScope: Optional[ResourceRegionScopeFilter] = None


class PermissionArnList(RootModel[List[String]]):
    root: List[String]


class Principal(BaseModel):
    creationTime: Optional[DateTime] = None
    external: Optional[Boolean] = None
    id: Optional[String] = None
    lastUpdatedTime: Optional[DateTime] = None
    resourceShareArn: Optional[String] = None


class PrincipalArnOrIdList(RootModel[List[String]]):
    root: List[String]


class PrincipalList(RootModel[List[Principal]]):
    root: List[Principal]


class PromotePermissionCreatedFromPolicyRequest(BaseModel):
    clientToken: Optional[String] = None
    name: String
    permissionArn: String


class RejectResourceShareInvitationRequest(BaseModel):
    clientToken: Optional[String] = None
    resourceShareInvitationArn: String


class ReplacePermissionAssociationsRequest(BaseModel):
    clientToken: Optional[String] = None
    fromPermissionArn: String
    fromPermissionVersion: Optional[Integer] = None
    toPermissionArn: String


class ReplacePermissionAssociationsWork(BaseModel):
    creationTime: Optional[DateTime] = None
    fromPermissionArn: Optional[String] = None
    fromPermissionVersion: Optional[String] = None
    id: Optional[String] = None
    lastUpdatedTime: Optional[DateTime] = None
    status: Optional[ReplacePermissionAssociationsWorkStatus] = None
    statusMessage: Optional[String] = None
    toPermissionArn: Optional[String] = None
    toPermissionVersion: Optional[String] = None


class ReplacePermissionAssociationsWorkIdList(RootModel[List[String]]):
    root: List[String]


class ReplacePermissionAssociationsWorkList(
    RootModel[List[ReplacePermissionAssociationsWork]]
):
    root: List[ReplacePermissionAssociationsWork]


class Resource(BaseModel):
    arn: Optional[String] = None
    creationTime: Optional[DateTime] = None
    lastUpdatedTime: Optional[DateTime] = None
    resourceGroupArn: Optional[String] = None
    resourceRegionScope: Optional[ResourceRegionScope] = None
    resourceShareArn: Optional[String] = None
    status: Optional[ResourceStatus] = None
    statusMessage: Optional[String] = None
    type: Optional[String] = None


class ResourceArnList(RootModel[List[String]]):
    root: List[String]


class ResourceList(RootModel[List[Resource]]):
    root: List[Resource]


class ResourceShareArnList(RootModel[List[String]]):
    root: List[String]


class ResourceShareAssociation(BaseModel):
    associatedEntity: Optional[String] = None
    associationType: Optional[ResourceShareAssociationType] = None
    creationTime: Optional[DateTime] = None
    external: Optional[Boolean] = None
    lastUpdatedTime: Optional[DateTime] = None
    resourceShareArn: Optional[String] = None
    resourceShareName: Optional[String] = None
    status: Optional[ResourceShareAssociationStatus] = None
    statusMessage: Optional[String] = None


class ResourceShareAssociationList(RootModel[List[ResourceShareAssociation]]):
    root: List[ResourceShareAssociation]


class ResourceShareInvitation(BaseModel):
    invitationTimestamp: Optional[DateTime] = None
    receiverAccountId: Optional[String] = None
    receiverArn: Optional[String] = None
    resourceShareArn: Optional[String] = None
    resourceShareAssociations: Optional[ResourceShareAssociationList] = None
    resourceShareInvitationArn: Optional[String] = None
    resourceShareName: Optional[String] = None
    senderAccountId: Optional[String] = None
    status: Optional[ResourceShareInvitationStatus] = None


class ResourceShareInvitationArnList(RootModel[List[String]]):
    root: List[String]


class ResourceShareInvitationList(RootModel[List[ResourceShareInvitation]]):
    root: List[ResourceShareInvitation]


class ServiceNameAndResourceType(BaseModel):
    resourceRegionScope: Optional[ResourceRegionScope] = None
    resourceType: Optional[String] = None
    serviceName: Optional[String] = None


class ServiceNameAndResourceTypeList(RootModel[List[ServiceNameAndResourceType]]):
    root: List[ServiceNameAndResourceType]


class SetDefaultPermissionVersionRequest(BaseModel):
    clientToken: Optional[String] = None
    permissionArn: String
    permissionVersion: Integer


class SetDefaultPermissionVersionResponse(BaseModel):
    clientToken: Optional[String] = None
    returnValue: Optional[Boolean] = None


class Tag(BaseModel):
    key: Optional[TagKey] = None
    value: Optional[TagValue] = None


class TagFilter(BaseModel):
    tagKey: Optional[TagKey] = None
    tagValues: Optional[TagValueList] = None


class TagFilters(RootModel[List[TagFilter]]):
    root: List[TagFilter]


class TagList(RootModel[List[Tag]]):
    root: List[Tag]


class TagResourceRequest(BaseModel):
    resourceArn: Optional[String] = None
    resourceShareArn: Optional[String] = None
    tags: TagList


class CreatepermissionPostRequest(BaseModel):
    clientToken: Optional[str] = Field(
        None,
        description='<p>Specifies a unique, case-sensitive identifier that you provide to ensure the idempotency of the request. This lets you safely retry the request without accidentally performing the same operation a second time. Passing the same value to a later call to an operation requires that you also pass the same value for all other parameters. We recommend that you use a <a href="https://wikipedia.org/wiki/Universally_unique_identifier">UUID type of value.</a>.</p> <p>If you don\'t provide this value, then Amazon Web Services generates a random one for you.</p> <p>If you retry the operation with the same <code>ClientToken</code>, but with different parameters, the retry fails with an <code>IdempotentParameterMismatch</code> error.</p>',
    )
    name: constr(pattern=r'[\w.-]*', min_length=1, max_length=36) = Field(
        ...,
        description='Specifies the name of the customer managed permission. The name must be unique within the Amazon Web Services Region.',
    )
    policyTemplate: str = Field(
        ...,
        description='<p>A string in JSON format string that contains the following elements of a resource-based policy:</p> <ul> <li> <p> <b>Effect</b>: must be set to <code>ALLOW</code>.</p> </li> <li> <p> <b>Action</b>: specifies the actions that are allowed by this customer managed permission. The list must contain only actions that are supported by the specified resource type. For a list of all actions supported by each resource type, see <a href="https://docs.aws.amazon.com/service-authorization/latest/reference/reference_policies_actions-resources-contextkeys.html">Actions, resources, and condition keys for Amazon Web Services services</a> in the <i>Identity and Access Management User Guide</i>.</p> </li> <li> <p> <b>Condition</b>: (optional) specifies conditional parameters that must evaluate to true when a user attempts an action for that action to be allowed. For more information about the Condition element, see <a href="https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_elements_condition.html">IAM policies: Condition element</a> in the <i>Identity and Access Management User Guide</i>.</p> </li> </ul> <p>This template can\'t include either the <code>Resource</code> or <code>Principal</code> elements. Those are both filled in by RAM when it instantiates the resource-based policy on each resource shared using this managed permission. The <code>Resource</code> comes from the ARN of the specific resource that you are sharing. The <code>Principal</code> comes from the list of identities added to the resource share.</p>',
    )
    resourceType: str = Field(
        ...,
        description='<p>Specifies the name of the resource type that this customer managed permission applies to.</p> <p>The format is <code> <i>&lt;service-code&gt;</i>:<i>&lt;resource-type&gt;</i> </code> and is not case sensitive. For example, to specify an Amazon EC2 Subnet, you can use the string <code>ec2:subnet</code>. To see the list of valid values for this parameter, query the <a>ListResourceTypes</a> operation.</p>',
    )
    tags: Optional[List[Tag]] = Field(
        None,
        description='Specifies a list of one or more tag key and value pairs to attach to the permission.',
    )


class CreateresourcesharePostRequest(BaseModel):
    allowExternalPrincipals: Optional[bool] = Field(
        None,
        description='Specifies whether principals outside your organization in Organizations can be associated with a resource share. A value of <code>true</code> lets you share with individual Amazon Web Services accounts that are <i>not</i> in your organization. A value of <code>false</code> only has meaning if your account is a member of an Amazon Web Services Organization. The default value is <code>true</code>.',
    )
    clientToken: Optional[str] = Field(
        None,
        description='<p>Specifies a unique, case-sensitive identifier that you provide to ensure the idempotency of the request. This lets you safely retry the request without accidentally performing the same operation a second time. Passing the same value to a later call to an operation requires that you also pass the same value for all other parameters. We recommend that you use a <a href="https://wikipedia.org/wiki/Universally_unique_identifier">UUID type of value.</a>.</p> <p>If you don\'t provide this value, then Amazon Web Services generates a random one for you.</p> <p>If you retry the operation with the same <code>ClientToken</code>, but with different parameters, the retry fails with an <code>IdempotentParameterMismatch</code> error.</p>',
    )
    name: str = Field(..., description='Specifies the name of the resource share.')
    permissionArns: Optional[List[String]] = Field(
        None,
        description='Specifies the <a href="https://docs.aws.amazon.com/general/latest/gr/aws-arns-and-namespaces.html">Amazon Resource Names (ARNs)</a> of the RAM permission to associate with the resource share. If you do not specify an ARN for the permission, RAM automatically attaches the default version of the permission for each resource type. You can associate only one permission with each resource type included in the resource share.',
    )
    principals: Optional[List[String]] = Field(
        None,
        description='<p>Specifies a list of one or more principals to associate with the resource share.</p> <p>You can include the following values:</p> <ul> <li> <p>An Amazon Web Services account ID, for example: <code>123456789012</code> </p> </li> <li> <p>An <a href="https://docs.aws.amazon.com/general/latest/gr/aws-arns-and-namespaces.html">Amazon Resource Name (ARN)</a> of an organization in Organizations, for example: <code>organizations::123456789012:organization/o-exampleorgid</code> </p> </li> <li> <p>An ARN of an organizational unit (OU) in Organizations, for example: <code>organizations::123456789012:ou/o-exampleorgid/ou-examplerootid-exampleouid123</code> </p> </li> <li> <p>An ARN of an IAM role, for example: <code>iam::123456789012:role/rolename</code> </p> </li> <li> <p>An ARN of an IAM user, for example: <code>iam::123456789012user/username</code> </p> </li> </ul> <note> <p>Not all resource types can be shared with IAM roles and users. For more information, see <a href="https://docs.aws.amazon.com/ram/latest/userguide/permissions.html#permissions-rbp-supported-resource-types">Sharing with IAM roles and users</a> in the <i>Resource Access Manager User Guide</i>.</p> </note>',
    )
    resourceArns: Optional[List[String]] = Field(
        None,
        description='Specifies a list of one or more ARNs of the resources to associate with the resource share.',
    )
    tags: Optional[List[Tag]] = Field(
        None,
        description="Specifies one or more tags to attach to the resource share itself. It doesn't attach the tags to the resources associated with the resource share.",
    )


class GetresourcesharesPostRequest(BaseModel):
    maxResults: Optional[conint(ge=1, le=500)] = Field(
        None,
        description='Specifies the total number of results that you want included on each page of the response. If you do not include this parameter, it defaults to a value that is specific to the operation. If additional items exist beyond the number you specify, the <code>NextToken</code> response element is returned with a value (not null). Include the specified value as the <code>NextToken</code> request parameter in the next call to the operation to get the next part of the results. Note that the service might return fewer results than the maximum even when there are more results available. You should check <code>NextToken</code> after every operation to ensure that you receive all of the results.',
    )
    name: Optional[str] = Field(
        None,
        description='Specifies the name of an individual resource share that you want to retrieve details about.',
    )
    nextToken: Optional[str] = Field(
        None,
        description="Specifies that you want to receive the next page of results. Valid only if you received a <code>NextToken</code> response in the previous request. If you did, it indicates that more output is available. Set this parameter to the value provided by the previous call's <code>NextToken</code> response to request the next page of results.",
    )
    permissionArn: Optional[str] = Field(
        None,
        description='Specifies that you want to retrieve details of only those resource shares that use the managed permission with this <a href="https://docs.aws.amazon.com/general/latest/gr/aws-arns-and-namespaces.html">Amazon Resource Name (ARN)</a>.',
    )
    permissionVersion: Optional[int] = Field(
        None,
        description='Specifies that you want to retrieve details for only those resource shares that use the specified version of the managed permission.',
    )
    resourceOwner: ResourceOwner = Field(
        ...,
        description='<p>Specifies that you want to retrieve details of only those resource shares that match the following:</p> <ul> <li> <p> <b> <code>SELF</code> </b> – resource shares that your account shares with other accounts</p> </li> <li> <p> <b> <code>OTHER-ACCOUNTS</code> </b> – resource shares that other accounts share with your account</p> </li> </ul>',
    )
    resourceShareArns: Optional[List[String]] = Field(
        None,
        description='Specifies the <a href="https://docs.aws.amazon.com/general/latest/gr/aws-arns-and-namespaces.html">Amazon Resource Names (ARNs)</a> of individual resource shares that you want information about.',
    )
    resourceShareStatus: Optional[ResourceShareStatus] = Field(
        None,
        description='Specifies that you want to retrieve details of only those resource shares that have this status.',
    )
    tagFilters: Optional[List[TagFilter]] = Field(
        None,
        description='Specifies that you want to retrieve details of only those resource shares that match the specified tag keys and values.',
    )


class TagresourcePostRequest(BaseModel):
    resourceArn: Optional[str] = Field(
        None,
        description='Specifies the <a href="https://docs.aws.amazon.com/general/latest/gr/aws-arns-and-namespaces.html">Amazon Resource Name (ARN)</a> of the managed permission that you want to add tags to. You must specify <i>either</i> <code>resourceArn</code>, or <code>resourceShareArn</code>, but not both.',
    )
    resourceShareArn: Optional[str] = Field(
        None,
        description='Specifies the <a href="https://docs.aws.amazon.com/general/latest/gr/aws-arns-and-namespaces.html">Amazon Resource Name (ARN)</a> of the resource share that you want to add tags to. You must specify <i>either</i> <code>resourceShareArn</code>, or <code>resourceArn</code>, but not both.',
    )
    tags: List[Tag] = Field(
        ...,
        description='A list of one or more tag key and value pairs. The tag key must be present and not be an empty string. The tag value must be present but can be an empty string.',
    )


class AcceptResourceShareInvitationResponse(BaseModel):
    clientToken: Optional[String] = None
    resourceShareInvitation: Optional[ResourceShareInvitation] = None


class AssociateResourceShareRequest(BaseModel):
    clientToken: Optional[String] = None
    principals: Optional[PrincipalArnOrIdList] = None
    resourceArns: Optional[ResourceArnList] = None
    resourceShareArn: String


class AssociateResourceShareResponse(BaseModel):
    clientToken: Optional[String] = None
    resourceShareAssociations: Optional[ResourceShareAssociationList] = None


class CreatePermissionRequest(BaseModel):
    clientToken: Optional[String] = None
    name: PermissionName
    policyTemplate: Policy
    resourceType: String
    tags: Optional[TagList] = None


class CreateResourceShareRequest(BaseModel):
    allowExternalPrincipals: Optional[Boolean] = None
    clientToken: Optional[String] = None
    name: String
    permissionArns: Optional[PermissionArnList] = None
    principals: Optional[PrincipalArnOrIdList] = None
    resourceArns: Optional[ResourceArnList] = None
    tags: Optional[TagList] = None


class DisassociateResourceShareRequest(BaseModel):
    clientToken: Optional[String] = None
    principals: Optional[PrincipalArnOrIdList] = None
    resourceArns: Optional[ResourceArnList] = None
    resourceShareArn: String


class DisassociateResourceShareResponse(BaseModel):
    clientToken: Optional[String] = None
    resourceShareAssociations: Optional[ResourceShareAssociationList] = None


class GetResourcePoliciesRequest(BaseModel):
    maxResults: Optional[MaxResults] = None
    nextToken: Optional[String] = None
    principal: Optional[String] = None
    resourceArns: ResourceArnList


class GetResourceShareAssociationsRequest(BaseModel):
    associationStatus: Optional[ResourceShareAssociationStatus] = None
    associationType: ResourceShareAssociationType
    maxResults: Optional[MaxResults] = None
    nextToken: Optional[String] = None
    principal: Optional[String] = None
    resourceArn: Optional[String] = None
    resourceShareArns: Optional[ResourceShareArnList] = None


class GetResourceShareAssociationsResponse(BaseModel):
    nextToken: Optional[String] = None
    resourceShareAssociations: Optional[ResourceShareAssociationList] = None


class GetResourceShareInvitationsRequest(BaseModel):
    maxResults: Optional[MaxResults] = None
    nextToken: Optional[String] = None
    resourceShareArns: Optional[ResourceShareArnList] = None
    resourceShareInvitationArns: Optional[ResourceShareInvitationArnList] = None


class GetResourceShareInvitationsResponse(BaseModel):
    nextToken: Optional[String] = None
    resourceShareInvitations: Optional[ResourceShareInvitationList] = None


class GetResourceSharesRequest(BaseModel):
    maxResults: Optional[MaxResults] = None
    name: Optional[String] = None
    nextToken: Optional[String] = None
    permissionArn: Optional[String] = None
    permissionVersion: Optional[Integer] = None
    resourceOwner: ResourceOwner
    resourceShareArns: Optional[ResourceShareArnList] = None
    resourceShareStatus: Optional[ResourceShareStatus] = None
    tagFilters: Optional[TagFilters] = None


class ListPendingInvitationResourcesResponse(BaseModel):
    nextToken: Optional[String] = None
    resources: Optional[ResourceList] = None


class ListPrincipalsRequest(BaseModel):
    maxResults: Optional[MaxResults] = None
    nextToken: Optional[String] = None
    principals: Optional[PrincipalArnOrIdList] = None
    resourceArn: Optional[String] = None
    resourceOwner: ResourceOwner
    resourceShareArns: Optional[ResourceShareArnList] = None
    resourceType: Optional[String] = None


class ListPrincipalsResponse(BaseModel):
    nextToken: Optional[String] = None
    principals: Optional[PrincipalList] = None


class ListReplacePermissionAssociationsWorkRequest(BaseModel):
    maxResults: Optional[MaxResults] = None
    nextToken: Optional[String] = None
    status: Optional[ReplacePermissionAssociationsWorkStatus] = None
    workIds: Optional[ReplacePermissionAssociationsWorkIdList] = None


class ListReplacePermissionAssociationsWorkResponse(BaseModel):
    nextToken: Optional[String] = None
    replacePermissionAssociationsWorks: Optional[
        ReplacePermissionAssociationsWorkList
    ] = None


class ListResourceTypesResponse(BaseModel):
    nextToken: Optional[String] = None
    resourceTypes: Optional[ServiceNameAndResourceTypeList] = None


class ListResourcesRequest(BaseModel):
    maxResults: Optional[MaxResults] = None
    nextToken: Optional[String] = None
    principal: Optional[String] = None
    resourceArns: Optional[ResourceArnList] = None
    resourceOwner: ResourceOwner
    resourceRegionScope: Optional[ResourceRegionScopeFilter] = None
    resourceShareArns: Optional[ResourceShareArnList] = None
    resourceType: Optional[String] = None


class ListResourcesResponse(BaseModel):
    nextToken: Optional[String] = None
    resources: Optional[ResourceList] = None


class RejectResourceShareInvitationResponse(BaseModel):
    clientToken: Optional[String] = None
    resourceShareInvitation: Optional[ResourceShareInvitation] = None


class ReplacePermissionAssociationsResponse(BaseModel):
    clientToken: Optional[String] = None
    replacePermissionAssociationsWork: Optional[ReplacePermissionAssociationsWork] = (
        None
    )


class ResourceShare(BaseModel):
    allowExternalPrincipals: Optional[Boolean] = None
    creationTime: Optional[DateTime] = None
    featureSet: Optional[ResourceShareFeatureSet] = None
    lastUpdatedTime: Optional[DateTime] = None
    name: Optional[String] = None
    owningAccountId: Optional[String] = None
    resourceShareArn: Optional[String] = None
    status: Optional[ResourceShareStatus] = None
    statusMessage: Optional[String] = None
    tags: Optional[TagList] = None


class ResourceShareList(RootModel[List[ResourceShare]]):
    root: List[ResourceShare]


class ResourceSharePermissionDetail(BaseModel):
    arn: Optional[String] = None
    creationTime: Optional[DateTime] = None
    defaultVersion: Optional[Boolean] = None
    featureSet: Optional[PermissionFeatureSet] = None
    isResourceTypeDefault: Optional[Boolean] = None
    lastUpdatedTime: Optional[DateTime] = None
    name: Optional[String] = None
    permission: Optional[String] = None
    permissionType: Optional[PermissionType] = None
    resourceType: Optional[String] = None
    status: Optional[PermissionStatus] = None
    tags: Optional[TagList] = None
    version: Optional[String] = None


class ResourceSharePermissionSummary(BaseModel):
    arn: Optional[String] = None
    creationTime: Optional[DateTime] = None
    defaultVersion: Optional[Boolean] = None
    featureSet: Optional[PermissionFeatureSet] = None
    isResourceTypeDefault: Optional[Boolean] = None
    lastUpdatedTime: Optional[DateTime] = None
    name: Optional[String] = None
    permissionType: Optional[PermissionType] = None
    resourceType: Optional[String] = None
    status: Optional[String] = None
    tags: Optional[TagList] = None
    version: Optional[String] = None


class UpdateResourceShareResponse(BaseModel):
    clientToken: Optional[String] = None
    resourceShare: Optional[ResourceShare] = None


class CreatePermissionResponse(BaseModel):
    clientToken: Optional[String] = None
    permission: Optional[ResourceSharePermissionSummary] = None


class CreatePermissionVersionResponse(BaseModel):
    clientToken: Optional[String] = None
    permission: Optional[ResourceSharePermissionDetail] = None


class CreateResourceShareResponse(BaseModel):
    clientToken: Optional[String] = None
    resourceShare: Optional[ResourceShare] = None


class GetPermissionResponse(BaseModel):
    permission: Optional[ResourceSharePermissionDetail] = None


class GetResourceSharesResponse(BaseModel):
    nextToken: Optional[String] = None
    resourceShares: Optional[ResourceShareList] = None


class PromotePermissionCreatedFromPolicyResponse(BaseModel):
    clientToken: Optional[String] = None
    permission: Optional[ResourceSharePermissionSummary] = None


class ResourceSharePermissionList(RootModel[List[ResourceSharePermissionSummary]]):
    root: List[ResourceSharePermissionSummary]


class ListPermissionVersionsResponse(BaseModel):
    nextToken: Optional[String] = None
    permissions: Optional[ResourceSharePermissionList] = None


class ListPermissionsResponse(BaseModel):
    nextToken: Optional[String] = None
    permissions: Optional[ResourceSharePermissionList] = None


class ListResourceSharePermissionsResponse(BaseModel):
    nextToken: Optional[String] = None
    permissions: Optional[ResourceSharePermissionList] = None
